### ISSUE TITLE
Fix the missing lang tag bug

### ISSUE THREAD

**Issue by Bystroushaak** [edeposit/edeposit.amqp.ltp#35]
Uncatched exception Soubor ``g:\safe-la\import-AIP-EPUB\process_313e2c8ea32847dd8f5e94ace25d92b1\mets.xml``
XPath:
``//mets:dmdSec[@ID='MODSMD_VOLUME_0001']/mets:mdWrap[@MDTYPE='MODS']/mets:xmlData/mods:mods/mods:language/mods:languageTerm[@type='code' and @authority='iso639-2b']``
Chyba: Hodnota je povinna

**Comment by Bystroushaak** [comment]
.. or maybe not

**Comment by jstavel** [comment]
To be, or not to be, that is the question

**Comment by Bystroushaak** [comment]
#22
